---

- set_fact:
    generate_vm_nodes: "{{vm_nodes is not defined}}"

- name: Define vm_nodes if not already defined
  when: generate_vm_nodes
  include_tasks: vm_nodes_tasks.yml
  loop: "{{flavors|dict2items}}"
  loop_control:
    loop_var: flavor

- debug:
    var: vm_nodes
  when: generate_vm_nodes
